-- Table Cocktail
INSERT ALL
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('bloody mary'                 ,  1.10, 'tumbler'      , 'long-drink'   , 'BloodyMary.jpg'              , 'Agiter les ingrédients dans un verre à mélange avec des glaçons (pour refroidir sans trop diluer). Verser dans le verre, puis ajouter à convenance sel de céleri, sel et poivre. Servir.'                                                                                                                                                                    , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('diabolo grenadine'           ,  0.80, 'tumbler'      , 'long-drink'   , 'DiaboloGrenadine.jpg'        , 'Versez la grenadine dans le verre et complétez avec de la limonade bien fraîche.'                                                                                                                                                                                                                                                                            , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('diabolo menthe'              ,  0.80, 'tumbler'      , 'long-drink'   , 'DiaboloMenthe.jpg'           , 'Versez la menthe dans le verre et complétez avec de la limonade bien fraîche.'                                                                                                                                                                                                                                                                               , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('americano'                   ,  1.10, 'tumbler'      , 'long-drink'   , 'Americano.jpg'               , 'Directement dans un tumbler rempli de glace, verser le Martini rouge, le Campari, compléter de Perrier. Décorer couper puis décorer avec d’une demi-tranche de citron et d’orange. Ajouter un agitateur.'                                                                                                                                                    , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('eggnog'                      ,  1.00, 'toddy'        , 'long-drink'   , 'eggnog.jpg'                  , 'Verser dans un shaker à moitié rempli de glace le sucre, le jaune d’œuf et le cognac.Shaker et verser dans un tumbler.Compléter avec du lait, ajouter la muscade et la cannelle et ajouter un agitateur. '                                                                                                                                                   , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('old fashioned'               ,  1.10, 'whisky'       , 'after-dinner' , 'OldFashioned.jpg'            , 'Écraser directement dans un verre Old Fashioned ¼ de morceau de sucre imbibé d’Angostura Bitter avec un peu de soda. Remplir le verre de glace, ajouter le Bourbon Whiskey. Remuer. Ajouter ½ tranche d’orange, la cerise à l’eau de vie et le zeste de citron.'                                                                                             , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('apple jack'                  ,  2.00, 'martini'      , 'short-drink'  , 'AppleJack.jpg'               , 'Versez dans un shaker rempli de glaçons le calvados, le jus de citron et la grenadine. Secouez énergiquement et versez dans un verre à martini en filtrant les glaçons. Servez immédiatement.'                                                                                                                                                               , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('jager bomb'                  ,  1.00, 'tumbler'      , 'long-drink'   , 'JagerBomb.jpg'               , 'Prenez un grand verre de type tumbler et remplissez-le de Red Bull jusqu’à environ un tiers du verre. Remplissez un verre à shot avec du Jagermeister. Plongez le verre à shot de Jagermeister dans le grand verre de Red Bull.'                                                                                                                             , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('margarita'                   ,  1.10, 'margarita'    , 'short-drink'  , 'Margarita.jpeg'              , 'Humidifier avec un citron et givrer au sel fin le bord du verre sur sa moitié seulement. Verser dans shaker à demi rempli de glace le jus de citron, le Cointreau puis la Tequila. Frapper et verser dans un verre à cocktail.'                                                                                                                              , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('pina colada'                 ,  2.00, 'tulipe'       , 'long-drink'   , 'pinacolada.jpg'              , 'Dans un mixer, versez les ingrédients avec 5 ou 6 glaçons et mixez le tout.'                                                                                                                                                                                                                                                                                 , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('negroni'                     ,  1.10, 'whisky'       , 'after-dinner' , 'Negroni.jpg'                 , 'Verser dans le verre à mélange rempli de glace le Martini rouge, le Campari puis le Gin. Remuer et filtrer le mélange dans le verre. Ajouter la demi-tranche d’orange.'                                                                                                                                                                                      , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('alpine negroni'              ,  1.30, 'whisky'       , 'after-dinner' , 'AlpineNegroni.jpg'           , 'Verser les ingredients dans un verre à mélange, ajouter de la glace et remuer. verser en filtrant dans le verre et ajouter la branche de romarin'                                                                                                                                                                                                            , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('blinker'                     ,  1.20, 'coupe'        , 'short-drink'  , 'Blinker.jpeg'                , 'Verser tout les ingredients et de la glace dans un shaker, verser dans le verre en filtrant dans la passoire, décorer avec les framboises'                                                                                                                                                                                                                   , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('pacha monte-carlos'          ,  2.00, 'tulipe'       , 'long-drink'   , 'montecarlo.jpg'              , 'Placer les pèches avec les autres ingredients dans un mixeur, ajouter la glace pilée et mixer, verser dans le verre et décorer avec 2 cerises.'                                                                                                                                                                                                              , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('mint julep'                  ,  1.20, 'whisky'       , 'long-drink'   , 'Mintjulep.jpeg'              , 'Directement dans le verre old fashioned, piler les feuilles de menthe et le sucre.Remplir de glace pilée.Verser le Bourbon Whiskey et décorer avec une cerise à l’eau de vie et feuilles de menthe fraîche. Ajouter une paille.'                                                                                                                             , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('blue hawaiian'               ,  1.00, 'tulipe'       , 'long-drink'   , 'blue-hawaii.jpg'             , 'Remplir le shaker de glace, ajouter le rhum, le curaçao, le sirop, le lait de coco et le jus d''ananas. Mélanger et verser le mélange dans le verre en flitrant avec la passoire. Décorer avec un quart de tranche d''ananas.'                                                                                                                               , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('miami beach'                 ,  1.20, 'martini'      , 'short-drink'  , 'Miami_Beach.jpg'             , 'Mettez les glaçons, le gin, le jus d''ananas et le sirop de sucre dans le shaker. Secouez avec énergie pendant 10 secondes. Filtrez et versez dans un verre martini.'                                                                                                                                                                                        , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('havana beach'                ,  1.30, 'martini'      , 'short-drink'  , 'havana-beach.jpg'            , 'Mettre des glaçons dans le shaker. Ajouter le rhum blanc, le jus d''ananas, le jus de citron vert et le sirop de sucre de canne. Frapper et verser dans un verre à cocktail.'                                                                                                                                                                                , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('swimming pool'               ,  2.00, 'tulipe'       , 'long-drink'   , 'Swimming pool.jpeg'          , 'Verser les ingrédients dans un shaker et mélanger 15 secondes.verser dans le verre et décorer avec une tranche d''ananas et une cerise.'                                                                                                                                                                                                                     , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('rusty nail'                  ,  1.10, 'whisky'       , 'after-dinner' , 'Rusty Nail.jpg'              , 'Remplir un verre de glace. Insérer le whisky puis la liqueur. Remuer à l''aide d''une cuillère à mélange. Insérer un long zeste de citron.'                                                                                                                                                                                                                  , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('vin chaud'                   ,  1.00, 'chope'        , 'after-dinner' , 'vin cho.jpg'                 , 'Faire chauffer le tout à feu moyen et constant pendant 20 minutes minimum, pour dissoudre le sucre et imprégner le vin de l''odeur de cannelle. Verser dans le verre en filtrant les clous de girofle et consommer...'                                                                                                                                       , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('hot buttered rum'            ,  2.00, 'toddy'        , 'after-dinner' , 'rum.jpg'                     , 'Verser directement dans le verre la cassonade et l''eau chaude. Remuer à l''aide d''une cuillère à mélange. Ajouter le rhum et le morceau de beurre. Ajouter selon votre goût de la cannelle, noix de muscade, gingembre et/ou gousse de vanille.'                                                                                                           , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('irish coffee'                ,  2.15, 'toddy'        , 'after-dinner' , 'irishcoffee.jpg'             , 'Mettre de l''eau chaude dans le verre pendant 5 minutes pour le préchauffer puis retirer l''eau. Chauffer le whisky avec le sucre sans le faire porter à ébullition. Verser le mélange dans le verre puis ajouter le café chaud. Fouetter la crème et venir la déposer sur le dessus du verre de type "chope". '                                             , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('espresso martini'            ,  1.20, 'martini'      , 'after-dinner' , 'martinicafé.jpg'             , 'Frapper au shaker avec quelques glaçons la vodka, la liqueur de café kahlua, le café et le sirop de sucre.Verser dans un verre à martini en filtrant la glace.'                                                                                                                                                                                              , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('amaro sour'                  ,  1.70, 'coupe'        , 'short-drink'  , 'amaro.jpeg'                  , 'Ajouter tout les ingrédients sauf l''oeuf dans le shaker rempli de glace et mélanger 15 secondes. Filtrer dans leshaker, ajouter le blanc de l''oeuf et remélanger 15 secondes. Verser dans la coupe et décorer avec la cerise. '                                                                                                                            , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('amaretto sour'               ,  1.10, 'whisky'       , 'short-drink'  , 'amaretto.jpeg'               , 'Placez quelques glaçons dans le verre. Frappez les ingrédients au shaker avec des glaçons puis versez dans le verre en retenant la glace du shaker.'                                                                                                                                                                                                         , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('beer float'                  ,  1.00, 'pilsner'      , 'long-drink'   , 'beer float.jpg'              , 'Versez la boisson dans le verre et ajoutez la boule de glace au dessus'                                                                                                                                                                                                                                                                                      , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('soda float'                  ,  1.00, 'pilsner'      , 'long-drink'   , 'lemonFloat.jpg'              , 'Versez la boisson dans le verre et ajoutez la boule de glace au dessus'                                                                                                                                                                                                                                                                                      , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('rio'                         ,  0.80, 'whisky'       , 'short-drink'  , 'RIO.jpg'                     , 'versez votre jus d''orange, ajoutez la grenadine puis la limonade. Ajoutez une ou deux rondelles de citron vert en décoration sur le bord. Remuer légèrement avec la paille et servez'                                                                                                                                                                       , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('fuzzy asshole'               ,  1.00, 'toddy'        , 'after-dinner' , 'fuzzy.jpg'                   , 'Remplir à moitié de café chaud et a moitié de schnapps, remuer.'                                                                                                                                                                                                                                                                                             , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('pink margarita'              ,  1.10, 'tumbler'      , 'short-drink'  , 'margaritarose.jpg'           , 'Verser les jus et le sirop, mélanger à la cuillère, complèter de limonade.'                                                                                                                                                                                                                                                                                  , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('august moon'                 ,  1.30, 'tumbler'      , 'long-drink'   , 'august-moon.jpg'             , 'Frappez les ingrédients au shaker, puis passez dans un verre rafraîchi.'                                                                                                                                                                                                                                                                                     , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('atomic freeze'               ,  3.00, 'ballon'       , 'long-drink'   , 'Atomic.jpg'                  , 'Laver et couper les fraises en morceaux. Ajouter dans le mixeur avec le restant des ingrédients et des glaçons. Mixer durant quelques secondes et verser dans de grands verres à vin. '                                                                                                                                                                      , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('sweet dreams'                ,  2.00, 'coupe'        , 'short-drink'  , 'sweetdreams.jpeg'            , 'Récupérer seulement le blanc de l''oeuf. Verser tous les ingrédients dans un shaker, sauf le champagne. Remuer vigoureusement sans glaçons pour monter le blanc d’œuf en neige. Ajouter des glaçons dans le shaker puis remuer. Verser le contenu dans le verre en le filtrant à l’aide d‘une passoire. Allonger le mocktail avec le champagne.'             , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('apple cobbler'               ,  1.10, 'whisky'       , 'short-drink'  , 'apple cobbler.jpg'           , 'Verser les ingrédient sur des glaçons. Bien mélanger et servir frais. Décorer avec la tranche de pomme'                                                                                                                                                                                                                                                      , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('apple fizz'                  ,  1.20, 'tumbler'      , 'long-drink'   , 'AppleFizz.jpeg'              , 'Mettre tout les ingredients dans le shaker avec de la glace. frappper et verser dans le verre.'                                                                                                                                                                                                                                                              , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('apricot beach'               ,  1.50, 'tumbler'      , 'long-drink'   , 'Abricot.jpeg'                , 'Récupérer seulement le jaune de l''oeuf. Mixer tout les ingrédients avec de la glace pilée jusqu''à obtenir une mousse onctueuse et verser dans le verre'                                                                                                                                                                                                    , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('banana sprint'               ,  2.00, 'tumbler'      , 'long-drink'   , 'banana.jpeg'                 , 'Mixer tout les ingrédients avec de la glace pilée jusqu''à obtenir une mousse onctueuse et verser dans le verre'                                                                                                                                                                                                                                             , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('bloody orange'               ,  1.10, 'tumbler'      , 'long-drink'   , 'bloody-orange.jpg'           , 'Mélanger tout les ingredients au shaker avec un peu de glace pilée et verser.'                                                                                                                                                                                                                                                                               , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('honeymoon'                   ,  1.20, 'tumbler'      , 'long-drink'   , 'honeymoon.jpeg'              , 'Frapper et passer dans le verre.'                                                                                                                                                                                                                                                                                                                            , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('alice'                       ,  1.30, 'tumbler'      , 'long-drink'   , 'Alice.jpg'                   , 'Frapper au shaker avec quelques glaçons la grenadine, le jus d''orange, le jus d''ananas et la crème liquide.Verser dans un verre highball.'                                                                                                                                                                                                                 , 'F')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('20e siecle'                  ,  1.00, 'martini'      , 'short-drink'  , '20esiecle.jpg'               , 'À l''aide d''un gobelet doseur, mesurer la quantité exacte d''ingrédients, puis les verser dans un shaker et agiter vigoureusement. verser dans le verre.'                                                                                                                                                                                                   , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('pussy cat'                   ,  1.20, 'whisky'       , 'short-drink'  , 'pussycat.jpg'                , 'Mettre tout les ingredients dans le shaker avec de la glace. frappper et filtrer dans le verre.'                                                                                                                                                                                                                                                             , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('buccaneer'                   ,  2.00, 'pilsner'      , 'long-drink'   , 'buc.jpeg'                    , 'Verser la biere dans le verre et ajouter le shooter de bacardi en remuant doucement'                                                                                                                                                                                                                                                                         , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('mai tai'                     ,  1.10, 'whisky'       , 'short-drink'  , 'classic-mai-tai.jpeg'        , 'Associez tous les ingrédients avec de la glace dans un shaker. Frappez et filtrez dans un verre à whisky.'                                                                                                                                                                                                                                                   , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('moscow mule'                 ,  2.00, 'chope'        , 'long-drink'   , 'mule.jpg'                    , 'Mettre la Glace dans un grand verre. Verser les ingrédients et remuer délicatement avec la cuillère à cocktail. Servir.'                                                                                                                                                                                                                                     , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('aperol spritz'               ,  1.40, 'ballon'       , 'long-drink'   , 'aperol.jpg'                  , 'Mettre 1 tranche d''orange et de la glace. Mettre l''Aperol.Remplir ensuite avec le Prosecco. Ajoutez un trait d''eau gazeuse et mélangez avec une cuillère. '                                                                                                                                                                                               , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('bamboo'                      ,  1.20, 'coupe'        , 'long-drink'   , 'bamboo.jpg'                  , 'Verser le vermouth et le sherry dans le verre à mélange avec quelques glaçons. Remuer soigneusement et ajouter l''angostura. Servir dans un verre à cocktail et décorer d''une olive.'                                                                                                                                                                       , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('pisco sour'                  ,  1.40, 'whisky'       , 'short-drink'  , 'pisco.jpg'                   , 'Ajouter le pisco, le jus de citron vert, le sirop de sucre et le blanc d''œuf dans un shaker et agiter pendant environ 15 secondes. Ajouter une poignée de glaçons et secouer à nouveau pendant 15 secondes. Filtrer le contenu dans un verre pré-refroidi. Verser l''Angostura Bitters sur le dessus de la mousse.'                                         , 'T')
	INTO P09_Cocktail(cocktail_nom, cocktail_prix, cocktail_verre, cocktail_categorie, cocktail_photo, cocktail_preparation, cocktail_alcoolise) VALUES ('caipirinha'                  ,  1.12, 'whisky'       , 'short-drink'  , 'caipi.jpeg'                  , 'Lavez le citron puis coupez-le en deux dans le sens de la hauteur. Enlevez la partie blanche centrale, source d’amertume. Découpez le citron en petits dés et placez-les dans le verre. Ajoutez le sirop de sucre. Ecraser dans le verre a l''aide du pilon. Ajouter de la glace et la cachaca. Mélanger et servez.'                                         , 'T')
SELECT * FROM dual;
/

-- Table Ustensile
INSERT ALL
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('verre a melange'             , 'melanger'     )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('couteau a tranches'          , 'couper'       )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('agitateur'                   , 'boire'        )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('shaker'                      , 'melanger'     )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('doseur'                      , 'doser'        )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('pilon'                       , 'ecraser'      )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('passoire'                    , 'filtrer'      )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('cuillere a melange'          , 'melanger'     )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('eplucheur'                   , 'decorer'      )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('paille'                      , 'boire'        )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('shooter'                     , 'doser'        )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('casserole'                   , 'chauffer'     )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('fouet'                       , 'melanger'     )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('cuillere a glace'            , 'doser'        )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('rape'                        , 'decorer'      )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('mixer'                       , 'melanger'     )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('siphon'                      , 'melanger'     )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('entonoir'                    , 'doser'        )
	INTO P09_Ustensile(ustensile_nom, ustensile_categorie) VALUES ('pince a glace'               , 'decorer'      )
SELECT * FROM dual;
/

-- Table Ingredient
INSERT ALL
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('vodka'                       , 'alcool'       ,     300.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de tomate'               , 'jus'          ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de citron'               , 'jus'          ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sauce worcestershire'        , 'condiment'    ,      80.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('tabasco'                     , 'condiment'    ,      80.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sel de celeri'               , 'epice'        ,   50000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sel'                         , 'epice'        ,   50000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('poivre'                      , 'epice'        ,   50000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('limonade'                    , 'soda'         ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sirop de menthe'             , 'sirop'        ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sirop de grenadine'          , 'sirop'        ,      80.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('bitter campari'              , 'alcool'       ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('martini rouge'               , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('perrier'                     , 'diluant'      ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('tranche d''orange'           , 'fruit'        ,       5.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('tranche de citron'           , 'fruit'        ,      15.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('lait'                        , 'diluant'      ,     300.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('oeuf'                        , 'aliment'      ,      12.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('cognac'                      , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sucre'                       , 'edulcorant'   , 1000000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('cannelle'                    , 'epice'        ,   50000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('muscade'                     , 'epice'        ,   50000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('morceau de sucre'            , 'edulcorant'   ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('bourbon whiskey'             , 'alcool'       ,     300.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('angostura bitter'            , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('citron'                      , 'fruit'        ,      15.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('cerise a l''eau de vie'      , 'fruit'        ,      30.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('calvados'                    , 'alcool'       ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('red bull'                    , 'diluant'      ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jagermeister'                , 'alcool'       ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('tequila'                     , 'alcool'       ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('cointreau'                   , 'alcool'       ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('rhum'                        , 'alcool'       ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus d''ananas'               , 'jus'          ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('creme de coco'               , 'alcool'       ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('gin'                         , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('liqueur de gentiane'         , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('americano bianco'            , 'alcool'       ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('genepi'                      , 'alcool'       ,      50.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('creme de menthe'             , 'alcool'       ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('lemon bitter'                , 'diluant'      ,      80.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('branche de romarin '         , 'epice'        ,      10.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de pamplemousse'         , 'jus'          ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('framboises'                  , 'fruit'        ,      50.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sirop de sucre'              , 'sirop'        ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('peche au sirop'              , 'aliment'      ,  150000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('cerise'                      , 'fruit'        ,      50.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('feuille de menthe'           , 'epice'        ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('curacao bleu'                , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('lait de coco'                , 'diluant'      ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('tranche d''ananas'           , 'fruit'        ,      20.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de citron vert'          , 'jus'          ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('creme liquide'               , 'aliment'      ,      50.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('scotch whisky'               , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('liqueur de whisky'           , 'alcool'       ,      70.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('vin rouge'                   , 'alcool'       ,     300.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('clou de girofle'             , 'epice'        ,      40.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('cassonade'                   , 'edulcorant'   ,  500000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('beurre'                      , 'aliment'      ,  500000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('gingembre'                   , 'epice'        ,   60000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('vanille gousse'              , 'epice'        ,   60000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('eau'                         , 'diluant'      ,     300.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('cafe'                        , 'diluant'      ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('liqueur de cafe'             , 'alcool'       ,      70.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('biere brune'                 , 'alcool'       ,     300.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('glace vanille'               , 'aliment'      ,  500000.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('biere blonde'                , 'alcool'       ,     300.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('amaro leger'                 , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('amaretto'                    , 'alcool'       ,      70.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus d''orange'               , 'jus'          ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('schnapps peche'              , 'alcool'       ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de cranberry'            , 'jus'          ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de pomme'                , 'jus'          ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de framboise'            , 'jus'          ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('miel'                        , 'edulcorant'   ,      70.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sirop d''orgeat'             , 'sirop'        ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('fraise'                      , 'fruit'        ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('champagne sans alcool'       , 'diluant'      ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de bissap'               , 'jus'          ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('bouton de rose seche'        , 'aliment'      ,      10.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('extrait de vanille'          , 'condiment'    ,      70.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('tranche de pomme'            , 'fruit'        ,      20.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus d''abricot'              , 'jus'          ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sirop d''orange sanguine'    , 'sirop'        ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de banane'               , 'jus'          ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sirop de citron'             , 'sirop'        ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('tranche de banane'           , 'fruit'        ,      20.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('jus de betterave'            , 'jus'          ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sirop d''erable'             , 'edulcorant'   ,      70.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('vin blanc'                   , 'alcool'       ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('liqueur de cacao blanc'      , 'alcool'       ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('bacardi citron'              , 'alcool'       ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('liqueur d''orange'           , 'alcool'       ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('ginger beer'                 , 'soda'         ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('prosecco'                    , 'alcool'       ,     200.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('aperol'                      , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('sherry'                      , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('vermouth sec'                , 'alcool'       ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('olive'                       , 'aliment'      ,     100.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('pisco'                       , 'alcool'       ,     120.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('cachaca'                     , 'alcool'       ,     150.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('tranche de citron vert'      , 'fruit'        ,      15.00)
	INTO P09_Ingredient(ingredient_nom, ingredient_type, ingredient_stock) VALUES ('citron vert'                 , 'fruit'        ,      12.00)
SELECT * FROM dual;
/

-- Table Compose
INSERT ALL
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody mary'                 , 'vodka'                       ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody mary'                 , 'jus de tomate'               ,       7.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody mary'                 , 'jus de citron'               ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody mary'                 , 'sauce worcestershire'        ,       0.30)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody mary'                 , 'tabasco'                     ,       0.30)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody mary'                 , 'sel de celeri'               ,      20.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody mary'                 , 'sel'                         ,      20.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody mary'                 , 'poivre'                      ,      20.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('americano'                   , 'martini rouge'               ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('americano'                   , 'bitter campari'              ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('americano'                   , 'perrier'                     ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('americano'                   , 'tranche d''orange'           ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('americano'                   , 'tranche de citron'           ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('eggnog'                      , 'lait'                        ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('eggnog'                      , 'oeuf'                        ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('eggnog'                      , 'cognac'                      ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('eggnog'                      , 'sucre'                       ,    5000.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('eggnog'                      , 'cannelle'                    ,      20.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('eggnog'                      , 'muscade'                     ,      20.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('diabolo grenadine'           , 'sirop de grenadine'          ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('diabolo grenadine'           , 'limonade'                    ,      15.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('diabolo menthe'              , 'limonade'                    ,      15.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('diabolo menthe'              , 'sirop de menthe'             ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('old fashioned'               , 'morceau de sucre'            ,       0.25)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('old fashioned'               , 'angostura bitter'            ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('old fashioned'               , 'perrier'                     ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('old fashioned'               , 'bourbon whiskey'             ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('old fashioned'               , 'tranche d''orange'           ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('old fashioned'               , 'citron'                      ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('old fashioned'               , 'cerise a l''eau de vie'      ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple jack'                  , 'calvados'                    ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple jack'                  , 'sirop de grenadine'          ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple jack'                  , 'jus de citron'               ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('jager bomb'                  , 'jagermeister'                ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('jager bomb'                  , 'red bull'                    ,      15.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('margarita'                   , 'tequila'                     ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('margarita'                   , 'jus de citron'               ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('margarita'                   , 'cointreau'                   ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('margarita'                   , 'sel'                         ,      10.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('margarita'                   , 'citron'                      ,       0.15)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pina colada'                 , 'rhum'                        ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pina colada'                 , 'jus d''ananas'               ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pina colada'                 , 'creme de coco'               ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('negroni'                     , 'bitter campari'              ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('negroni'                     , 'gin'                         ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('negroni'                     , 'martini rouge'               ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('negroni'                     , 'tranche d''orange'           ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alpine negroni'              , 'gin'                         ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alpine negroni'              , 'liqueur de gentiane'         ,       2.25)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alpine negroni'              , 'americano bianco'            ,       2.25)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alpine negroni'              , 'genepi'                      ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alpine negroni'              , 'creme de menthe'             ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alpine negroni'              , 'lemon bitter'                ,       0.02)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alpine negroni'              , 'branche de romarin '         ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('blinker'                     , 'bourbon whiskey'             ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('blinker'                     , 'jus de pamplemousse'         ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('blinker'                     , 'sirop de grenadine'          ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pacha monte-carlos'          , 'peche au sirop'              ,   60000.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pacha monte-carlos'          , 'sirop de sucre'              ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pacha monte-carlos'          , 'martini rouge'               ,      10.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pacha monte-carlos'          , 'cerise'                      ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pacha monte-carlos'          , 'calvados'                    ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('mint julep'                  , 'feuille de menthe'           ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('mint julep'                  , 'sucre'                       ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('mint julep'                  , 'bourbon whiskey'             ,       8.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('mint julep'                  , 'cerise a l''eau de vie'      ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('blue hawaiian'               , 'rhum'                        ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('blue hawaiian'               , 'jus d''ananas'               ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('blue hawaiian'               , 'curacao bleu'                ,       8.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('blue hawaiian'               , 'lait de coco'                ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('blue hawaiian'               , 'sirop de sucre'              ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('blue hawaiian'               , 'tranche d''ananas'           ,       0.25)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('miami beach'                 , 'gin'                         ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('miami beach'                 , 'jus d''ananas'               ,       2.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('miami beach'                 , 'sirop de sucre'              ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('havana beach'                , 'jus d''ananas'               ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('havana beach'                , 'jus de citron vert'          ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('havana beach'                , 'rhum'                        ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('havana beach'                , 'sirop de sucre'              ,       0.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('swimming pool'               , 'vodka'                       ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('swimming pool'               , 'rhum'                        ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('swimming pool'               , 'curacao bleu'                ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('swimming pool'               , 'creme de coco'               ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('swimming pool'               , 'creme liquide'               ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('swimming pool'               , 'jus d''ananas'               ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('swimming pool'               , 'tranche d''ananas'           ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('swimming pool'               , 'cerise a l''eau de vie'      ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('rusty nail'                  , 'scotch whisky'               ,       4.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('rusty nail'                  , 'liqueur de whisky'           ,       2.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('rusty nail'                  , 'citron'                      ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('vin chaud'                   , 'vin rouge'                   ,      15.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('vin chaud'                   , 'jus de citron'               ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('vin chaud'                   , 'clou de girofle'             ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('vin chaud'                   , 'sucre'                       ,   10000.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('vin chaud'                   , 'cannelle'                    ,      60.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('hot buttered rum'            , 'rhum'                        ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('hot buttered rum'            , 'cassonade'                   ,    5000.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('hot buttered rum'            , 'beurre'                      ,    6000.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('hot buttered rum'            , 'cannelle'                    ,      20.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('hot buttered rum'            , 'gingembre'                   ,      20.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('hot buttered rum'            , 'muscade'                     ,      20.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('hot buttered rum'            , 'vanille gousse'              ,      20.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('hot buttered rum'            , 'eau'                         ,      10.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('irish coffee'                , 'creme liquide'               ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('irish coffee'                , 'cafe'                        ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('irish coffee'                , 'bourbon whiskey'             ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('irish coffee'                , 'morceau de sucre'            ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('espresso martini'            , 'vodka'                       ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('espresso martini'            , 'liqueur de cafe'             ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('espresso martini'            , 'cafe'                        ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('espresso martini'            , 'sirop de sucre'              ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('amaro sour'                  , 'oeuf'                        ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('amaro sour'                  , 'bourbon whiskey'             ,       2.20)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('amaro sour'                  , 'jus de citron'               ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('amaro sour'                  , 'sirop de sucre'              ,       0.70)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('amaro sour'                  , 'amaro leger'                 ,       4.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('amaro sour'                  , 'cerise a l''eau de vie'      ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('amaretto sour'               , 'amaretto'                    ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('amaretto sour'               , 'jus de citron'               ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('amaretto sour'               , 'sirop de sucre'              ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('beer float'                  , 'biere brune'                 ,      50.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('beer float'                  , 'glace vanille'               ,   30000.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('soda float'                  , 'glace vanille'               ,   30000.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('soda float'                  , 'limonade'                    ,      50.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('rio'                         , 'jus d''orange'               ,      15.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('rio'                         , 'limonade'                    ,       8.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('rio'                         , 'sirop de grenadine'          ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('rio'                         , 'tranche de citron vert'      ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('fuzzy asshole'               , 'cafe'                        ,      12.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('fuzzy asshole'               , 'schnapps peche'              ,      12.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pink margarita'              , 'jus de citron'               ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pink margarita'              , 'jus de cranberry'            ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pink margarita'              , 'sirop de sucre'              ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pink margarita'              , 'limonade'                    ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('august moon'                 , 'jus de pomme'                ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('august moon'                 , 'jus de framboise'            ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('august moon'                 , 'jus de citron vert'          ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('august moon'                 , 'miel'                        ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('atomic freeze'               , 'jus d''ananas'               ,      40.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('atomic freeze'               , 'jus de pomme'                ,      24.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('atomic freeze'               , 'sirop d''orgeat'             ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('atomic freeze'               , 'fraise'                      ,      10.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('sweet dreams'                , 'jus de bissap'               ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('sweet dreams'                , 'jus de citron vert'          ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('sweet dreams'                , 'champagne sans alcool'       ,       9.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('sweet dreams'                , 'oeuf'                        ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('sweet dreams'                , 'bouton de rose seche'        ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple cobbler'               , 'jus de pomme'                ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple cobbler'               , 'jus de citron'               ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple cobbler'               , 'extrait de vanille'          ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple fizz'                  , 'jus de pomme'                ,       8.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple fizz'                  , 'jus de citron'               ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple fizz'                  , 'extrait de vanille'          ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apple fizz'                  , 'oeuf'                        ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apricot beach'               , 'jus d''abricot'              ,      10.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apricot beach'               , 'sirop d''orange sanguine'    ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apricot beach'               , 'creme liquide'               ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('apricot beach'               , 'oeuf'                        ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('banana sprint'               , 'jus de banane'               ,      10.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('banana sprint'               , 'sirop de citron'             ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('banana sprint'               , 'oeuf'                        ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('banana sprint'               , 'tranche de banane'           ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody orange'               , 'jus d''orange'               ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody orange'               , 'jus de betterave'            ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bloody orange'               , 'jus de pomme'                ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('honeymoon'                   , 'jus d''orange'               ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('honeymoon'                   , 'jus de pomme'                ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('honeymoon'                   , 'sirop d''erable'             ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('honeymoon'                   , 'jus de citron vert'          ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alice'                       , 'sirop de grenadine'          ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alice'                       , 'jus d''orange'               ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alice'                       , 'jus d''ananas'               ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('alice'                       , 'creme liquide'               ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('20e siecle'                  , 'vin blanc'                   ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('20e siecle'                  , 'liqueur de cacao blanc'      ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('20e siecle'                  , 'gin'                         ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('20e siecle'                  , 'jus de citron'               ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pussy cat'                   , 'bourbon whiskey'             ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pussy cat'                   , 'amaretto'                    ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pussy cat'                   , 'jus d''orange'               ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pussy cat'                   , 'jus de citron'               ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pussy cat'                   , 'cerise a l''eau de vie'      ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('buccaneer'                   , 'biere blonde'                ,      50.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('buccaneer'                   , 'bacardi citron'              ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('mai tai'                     , 'rhum'                        ,       4.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('mai tai'                     , 'liqueur d''orange'           ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('mai tai'                     , 'jus de citron vert'          ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('mai tai'                     , 'sirop d''orgeat'             ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('moscow mule'                 , 'ginger beer'                 ,      50.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('moscow mule'                 , 'vodka'                       ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('moscow mule'                 , 'jus de citron'               ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('aperol spritz'               , 'aperol'                      ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('aperol spritz'               , 'prosecco'                    ,      12.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('aperol spritz'               , 'perrier'                     ,       3.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('aperol spritz'               , 'tranche d''orange'           ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bamboo'                      , 'sherry'                      ,       4.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bamboo'                      , 'vermouth sec'                ,       4.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bamboo'                      , 'angostura bitter'            ,       0.10)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('bamboo'                      , 'olive'                       ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pisco sour'                  , 'pisco'                       ,       5.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pisco sour'                  , 'jus de citron vert'          ,       2.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pisco sour'                  , 'sirop de sucre'              ,       1.50)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pisco sour'                  , 'oeuf'                        ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('pisco sour'                  , 'angostura bitter'            ,       0.10)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('caipirinha'                  , 'cachaca'                     ,       6.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('caipirinha'                  , 'sirop de sucre'              ,       2.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('caipirinha'                  , 'tranche de citron vert'      ,       1.00)
	INTO P09_Compose(cocktail_nom, ingredient_nom, quantite) VALUES ('caipirinha'                  , 'citron vert'                 ,       1.00)
SELECT * FROM dual;
/

-- Table Necessite
INSERT ALL
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('bloody mary'                 , 'verre a melange'             )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('americano'                   , 'agitateur'                   )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('americano'                   , 'couteau a tranches'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('americano'                   , 'doseur'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('eggnog'                      , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('old fashioned'               , 'doseur'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('old fashioned'               , 'eplucheur'                   )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('old fashioned'               , 'couteau a tranches'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('apple jack'                  , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('apple jack'                  , 'doseur'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('jager bomb'                  , 'shooter'                     )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('margarita'                   , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('margarita'                   , 'couteau a tranches'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pina colada'                 , 'mixer'                       )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pina colada'                 , 'paille'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('negroni'                     , 'verre a melange'             )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('negroni'                     , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('alpine negroni'              , 'verre a melange'             )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('alpine negroni'              , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('blinker'                     , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('blinker'                     , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pacha monte-carlos'          , 'doseur'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pacha monte-carlos'          , 'paille'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pacha monte-carlos'          , 'mixer'                       )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('mint julep'                  , 'pilon'                       )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('mint julep'                  , 'paille'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('blue hawaiian'               , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('blue hawaiian'               , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('blue hawaiian'               , 'doseur'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('miami beach'                 , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('miami beach'                 , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('havana beach'                , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('havana beach'                , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('swimming pool'               , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('rusty nail'                  , 'cuillere a melange'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('rusty nail'                  , 'eplucheur'                   )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('vin chaud'                   , 'casserole'                   )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('vin chaud'                   , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('hot buttered rum'            , 'cuillere a melange'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('hot buttered rum'            , 'casserole'                   )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('irish coffee'                , 'casserole'                   )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('irish coffee'                , 'fouet'                       )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('espresso martini'            , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('espresso martini'            , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('amaro sour'                  , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('amaro sour'                  , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('amaretto sour'               , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('beer float'                  , 'cuillere a glace'            )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('soda float'                  , 'cuillere a glace'            )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('rio'                         , 'paille'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('beer float'                  , 'paille'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('soda float'                  , 'paille'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('fuzzy asshole'               , 'cuillere a melange'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pink margarita'              , 'cuillere a melange'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('august moon'                 , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('august moon'                 , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('atomic freeze'               , 'mixer'                       )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('sweet dreams'                , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('sweet dreams'                , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('apple cobbler'               , 'cuillere a melange'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('apple cobbler'               , 'couteau a tranches'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('apple fizz'                  , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('apple fizz'                  , 'couteau a tranches'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('apricot beach'               , 'mixer'                       )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('banana sprint'               , 'mixer'                       )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('banana sprint'               , 'couteau a tranches'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('bloody orange'               , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('honeymoon'                   , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('alice'                       , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('20e siecle'                  , 'doseur'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('20e siecle'                  , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pussy cat'                   , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pussy cat'                   , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('buccaneer'                   , 'cuillere a melange'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('buccaneer'                   , 'shooter'                     )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('mai tai'                     , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('moscow mule'                 , 'verre a melange'             )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('aperol spritz'               , 'cuillere a melange'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('bamboo'                      , 'verre a melange'             )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('bamboo'                      , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pisco sour'                  , 'shaker'                      )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('pisco sour'                  , 'passoire'                    )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('caipirinha'                  , 'couteau a tranches'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('caipirinha'                  , 'pilon'                       )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('caipirinha'                  , 'cuillere a melange'          )
	INTO P09_Necessite(cocktail_nom, ustensile_nom) VALUES ('caipirinha'                  , 'paille'                      )
SELECT * FROM dual;
/